### ISSUE TITLE
remove line-height declaration from common.css

### ISSUE THREAD

**Issue by jnurthen** [w3c/aria-common#18]
_From @jasonkiss on September 28, 2016 22:40_

The lovely new design for W3C specs sets a line-height of 1.5 in line 79 of [base.css](https://www.w3.org/StyleSheets/TR/2016/base.css). 

This is overwritten by a line-height of 1.2 set in line 4 of [/aria/common/css/common.css](https://github.com/w3c/aria/blob/master/common/css/common.css). 

The [mapping-tables.css](https://github.com/w3c/aria/blob/master/common/css/mapping-tables.css) sets a line-height of 1.4 on the `body` element (see line 1), and 1.3 for the items in the mapping table cells (see line 50). 

The smaller line-heights reduce legibility. Can we just remove the declarations from common.css and mapping-tables.css and let the 1.5 line-height be?

_Copied from original issue: w3c/aria#445_

**Comment by jnurthen** [comment]
@michael-n-cooper Any chance we can fix this? It has been raised to me as being an issue for readability of our specs again.

**Comment by michael-n-cooper** [comment]
I'm hesitant to make this change without review because I don't know exactly what might be impacted, since I can't really see why those line heights are there but they seem to be for specific situations. I'd rather have the original authors weigh in, which is @halindrome for common.css and @klown for mapping-tables.css. If those people say it's ok, then I'm fine for this change. If we don't hear back, then we could make a pull request with a review period then commit.

**Comment by jnurthen** [comment]
The changes in the our style sheets made the line spacing larger [1.2 vs unset] (compared to the old w3c stylesheet). With the "new" stylesheet the line spacing is now made smaller compared to the default [1.2 vs 1.5]

I'd suggest the reasons for them have probably been either forgotten or overcome by other changes.

I heard more complaints recently about the readability of our specs compared to other w3c specs and would like to address this.

**Comment by klown** [comment]
Hey @michael-n-cooper,

To the best of my recollection, the only thing I did with `mapping-tables.css` is make sure that the url for the disclosure triangle graphic was correct.  I have no opinion about line heights.

My contribution to the UI for the mapping tables was based on the work that @jasonkiss had done for the HTML-AAM.  Since he wants to change these line heights -- [see the first comment](https://github.com/w3c/aria-common/issues/18#issue-387043178) at the top of this issue -- I defer to him.
